spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate


bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  sysname: 'INVEST_BOT'
  attachements-path: attachements

openapi:
  service:
    title: 'bot-admin api'
    version: '1.0.1'

server:
  port: ${PORT:5000}